-- project 2 task1
use  modelcarsdb;
SELECT COUNT(*) AS total_employees
FROM employees;

-- task2 List all employees with their basic information.

SELECT employeeNumber, firstName, lastName, email, jobTitle, officeCode
FROM employees;

-- task3 Count the number of employees holding each job title.
SELECT jobTitle, COUNT(*) AS numberOfEmployees
FROM employees
GROUP BY jobTitle;

-- task4 Find the employees who don't have a manager (reports To is NULL).
SELECT employeeNumber, firstName, lastName, email, jobTitle, officeCode
FROM employees
WHERE reportsTo IS NULL;

-- task5 Calculate total sales generated by each sales representative
SELECT 
    e.employeeNumber,
    e.firstName,
    e.lastName,
    SUM(od.priceEach * od.quantityOrdered) AS total_sales
FROM 
    employees e
JOIN 
    customers c ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN 
    orders o ON c.customerNumber = o.customerNumber
JOIN 
    orderdetails od ON o.orderNumber = od.orderNumber
GROUP BY 
    e.employeeNumber, e.firstName, e.lastName
ORDER BY 
    total_sales DESC;
    
    -- task6 Find the most profitable sales representative based on total sales
    SELECT sales_rep, SUM(sale_amount) AS total_sales
FROM sales
GROUP BY sales_rep
ORDER BY total_sales DESC
LIMIT 1;

    -- task7. Find the names of all employees who have sold more than the average sales amount for their office.
SELECT e.employee_name
FROM employees e
INNER JOIN (
  SELECT office_id, AVG(sale_amount) AS avg_sale_amount
  FROM sales
  GROUP BY office_id
) AS avg_sales
ON e.office_id = avg_sales.office_id
WHERE e.employee_id IN (
  SELECT sales_rep
  FROM sales s
  WHERE sale_amount > (
    SELECT avg_sale_amount
    FROM avg_sales
    WHERE avg_sales.office_id = s.office_id
  )
);



